### ISSUE TITLE
Model should reveal its data to a ViewModel using a specialized object.

### ISSUE THREAD

**Issue by aannenko** [aannenko/noughts-and-crosses#7]
**Summary**
Currently Game reveals its data to the ViewModel using a set of properties, methods and fields which is not very convenient and secure (ViewModel is able to change some of them and it can cause unexpected or faulty behavior of the game).
We can fix this by implementing a specialized object containing all the information that the ViewModel may need. This object should be created and filled with actual info in the end of every turn.

**Conditions**
1. We should have a specific object that will be revealed by a Game's property (e.g. State).
2. This object should contain all the information needed by the ViewModel part (hence, the View part): a copy of the field cells array, a copy of the players array, a copy of current player and a game state (if I forgot something, please add it here).
3. This object should be updated in the end of each player's turn so that the ViewModel part could get fresh info every time the turn ends.

**Comment by KassandraA** [comment]
I created a private field in Game object named 'state'. It has methods: 
- currentStatus (a game state, means status) 
- getCurrentPlayerName (a copy of current player)  
- getFieldCells (a copy of the field cells array)
These methods are used in ViewModel object. 
So from the mentioned above (in the paragraph 2) I didn't use a copy of the players array because it is used only in Model in Game object to set iterator variable. Is it ok?

And I'd be grateful if you could show me how someone can get access to my Game properties (e.g. currentStatus) from ViewModel object and change it.

And in paragraph 3 I didn't do anything because the getState public method (that returns state field) is always having the current state information.

**Comment by KassandraA** [comment]
Everything is working, it is now 2 human players and you cannot see status and players changes without refreshState at the end of each move (the finishTurn function).
